### ISSUE TITLE
[1.12] Crash on startup.

### ISSUE THREAD

**Issue by GigaOtomia** [Shadows-of-Fire/Singularities#4]
[crash-2018-07-16_12.37.07-client.txt](https://github.com/Shadows-of-Fire/Singularities/files/2198469/crash-2018-07-16_12.37.07-client.txt)

[singularities.cfg.txt](https://github.com/Shadows-of-Fire/Singularities/files/2198471/singularities.cfg.txt)
I'm relatively sure I did the config right.

**Comment by Shadows-of-Fire** [comment]
This line `conductive_iron_singularity, blockConductiveIron, 15600,singularities:singularity:8` is invalid, all entries must be separated by a comma followed by a space.  I'm gonna improve the crash that you just got so this error is more clear, because honestly without a message that's just confusing.
